# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('robox', '0001_squashed_0007_binaryfile_name'),
    ]

    operations = [
        migrations.AlterField(
                model_name='datafile',
                name='barcode',
                field=models.CharField(max_length=50),
        ),
    ]
